//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Administracion.ServicioWeb {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MiServicioSoap", Namespace="http://tempuri.org/")]
    public partial class MiServicio : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SerializarOperationCompleted;
        
        private System.Threading.SendOrPostCallback SerializarCorOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarCursoOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarCursoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarCursoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarCursosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarCursosOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogueoEmpleadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarEmpleadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegistrarEmpleadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarEmlpeadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarEmpleadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarAlumnoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarAlumnoOperationCompleted;
        
        private System.Threading.SendOrPostCallback InscripcionAlumnoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarInscripcionOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarSucursalOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarSucursalOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarSucursalOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarSucursalOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarSucursalesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MiServicio() {
            this.Url = global::Administracion.Properties.Settings.Default.Administracion_ServicioWeb_MiServicio;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SerializarCompletedEventHandler SerializarCompleted;
        
        /// <remarks/>
        public event SerializarCorCompletedEventHandler SerializarCorCompleted;
        
        /// <remarks/>
        public event AgregarCursoCompletedEventHandler AgregarCursoCompleted;
        
        /// <remarks/>
        public event EliminarCursoCompletedEventHandler EliminarCursoCompleted;
        
        /// <remarks/>
        public event BuscarCursoCompletedEventHandler BuscarCursoCompleted;
        
        /// <remarks/>
        public event ListarCursosCompletedEventHandler ListarCursosCompleted;
        
        /// <remarks/>
        public event ModificarCursosCompletedEventHandler ModificarCursosCompleted;
        
        /// <remarks/>
        public event LogueoEmpleadoCompletedEventHandler LogueoEmpleadoCompleted;
        
        /// <remarks/>
        public event BuscarEmpleadoCompletedEventHandler BuscarEmpleadoCompleted;
        
        /// <remarks/>
        public event RegistrarEmpleadoCompletedEventHandler RegistrarEmpleadoCompleted;
        
        /// <remarks/>
        public event ModificarEmlpeadoCompletedEventHandler ModificarEmlpeadoCompleted;
        
        /// <remarks/>
        public event EliminarEmpleadoCompletedEventHandler EliminarEmpleadoCompleted;
        
        /// <remarks/>
        public event AgregarAlumnoCompletedEventHandler AgregarAlumnoCompleted;
        
        /// <remarks/>
        public event BuscarAlumnoCompletedEventHandler BuscarAlumnoCompleted;
        
        /// <remarks/>
        public event InscripcionAlumnoCompletedEventHandler InscripcionAlumnoCompleted;
        
        /// <remarks/>
        public event ListarInscripcionCompletedEventHandler ListarInscripcionCompleted;
        
        /// <remarks/>
        public event AgregarSucursalCompletedEventHandler AgregarSucursalCompleted;
        
        /// <remarks/>
        public event EliminarSucursalCompletedEventHandler EliminarSucursalCompleted;
        
        /// <remarks/>
        public event ModificarSucursalCompletedEventHandler ModificarSucursalCompleted;
        
        /// <remarks/>
        public event BuscarSucursalCompletedEventHandler BuscarSucursalCompleted;
        
        /// <remarks/>
        public event ListarSucursalesCompletedEventHandler ListarSucursalesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Serializar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Serializar(Cortos co, Especializados es) {
            this.Invoke("Serializar", new object[] {
                        co,
                        es});
        }
        
        /// <remarks/>
        public void SerializarAsync(Cortos co, Especializados es) {
            this.SerializarAsync(co, es, null);
        }
        
        /// <remarks/>
        public void SerializarAsync(Cortos co, Especializados es, object userState) {
            if ((this.SerializarOperationCompleted == null)) {
                this.SerializarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSerializarOperationCompleted);
            }
            this.InvokeAsync("Serializar", new object[] {
                        co,
                        es}, this.SerializarOperationCompleted, userState);
        }
        
        private void OnSerializarOperationCompleted(object arg) {
            if ((this.SerializarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SerializarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SerializarCor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cortos SerializarCor() {
            object[] results = this.Invoke("SerializarCor", new object[0]);
            return ((Cortos)(results[0]));
        }
        
        /// <remarks/>
        public void SerializarCorAsync() {
            this.SerializarCorAsync(null);
        }
        
        /// <remarks/>
        public void SerializarCorAsync(object userState) {
            if ((this.SerializarCorOperationCompleted == null)) {
                this.SerializarCorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSerializarCorOperationCompleted);
            }
            this.InvokeAsync("SerializarCor", new object[0], this.SerializarCorOperationCompleted, userState);
        }
        
        private void OnSerializarCorOperationCompleted(object arg) {
            if ((this.SerializarCorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SerializarCorCompleted(this, new SerializarCorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarCurso", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AgregarCurso(Cursos c) {
            this.Invoke("AgregarCurso", new object[] {
                        c});
        }
        
        /// <remarks/>
        public void AgregarCursoAsync(Cursos c) {
            this.AgregarCursoAsync(c, null);
        }
        
        /// <remarks/>
        public void AgregarCursoAsync(Cursos c, object userState) {
            if ((this.AgregarCursoOperationCompleted == null)) {
                this.AgregarCursoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarCursoOperationCompleted);
            }
            this.InvokeAsync("AgregarCurso", new object[] {
                        c}, this.AgregarCursoOperationCompleted, userState);
        }
        
        private void OnAgregarCursoOperationCompleted(object arg) {
            if ((this.AgregarCursoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarCursoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarCurso", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EliminarCurso(Cursos c) {
            this.Invoke("EliminarCurso", new object[] {
                        c});
        }
        
        /// <remarks/>
        public void EliminarCursoAsync(Cursos c) {
            this.EliminarCursoAsync(c, null);
        }
        
        /// <remarks/>
        public void EliminarCursoAsync(Cursos c, object userState) {
            if ((this.EliminarCursoOperationCompleted == null)) {
                this.EliminarCursoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarCursoOperationCompleted);
            }
            this.InvokeAsync("EliminarCurso", new object[] {
                        c}, this.EliminarCursoOperationCompleted, userState);
        }
        
        private void OnEliminarCursoOperationCompleted(object arg) {
            if ((this.EliminarCursoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarCursoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarCurso", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cursos BuscarCurso(string cod) {
            object[] results = this.Invoke("BuscarCurso", new object[] {
                        cod});
            return ((Cursos)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarCursoAsync(string cod) {
            this.BuscarCursoAsync(cod, null);
        }
        
        /// <remarks/>
        public void BuscarCursoAsync(string cod, object userState) {
            if ((this.BuscarCursoOperationCompleted == null)) {
                this.BuscarCursoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarCursoOperationCompleted);
            }
            this.InvokeAsync("BuscarCurso", new object[] {
                        cod}, this.BuscarCursoOperationCompleted, userState);
        }
        
        private void OnBuscarCursoOperationCompleted(object arg) {
            if ((this.BuscarCursoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarCursoCompleted(this, new BuscarCursoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarCursos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cursos[] ListarCursos() {
            object[] results = this.Invoke("ListarCursos", new object[0]);
            return ((Cursos[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarCursosAsync() {
            this.ListarCursosAsync(null);
        }
        
        /// <remarks/>
        public void ListarCursosAsync(object userState) {
            if ((this.ListarCursosOperationCompleted == null)) {
                this.ListarCursosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarCursosOperationCompleted);
            }
            this.InvokeAsync("ListarCursos", new object[0], this.ListarCursosOperationCompleted, userState);
        }
        
        private void OnListarCursosOperationCompleted(object arg) {
            if ((this.ListarCursosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarCursosCompleted(this, new ListarCursosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificarCursos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ModificarCursos(Cursos c) {
            this.Invoke("ModificarCursos", new object[] {
                        c});
        }
        
        /// <remarks/>
        public void ModificarCursosAsync(Cursos c) {
            this.ModificarCursosAsync(c, null);
        }
        
        /// <remarks/>
        public void ModificarCursosAsync(Cursos c, object userState) {
            if ((this.ModificarCursosOperationCompleted == null)) {
                this.ModificarCursosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarCursosOperationCompleted);
            }
            this.InvokeAsync("ModificarCursos", new object[] {
                        c}, this.ModificarCursosOperationCompleted, userState);
        }
        
        private void OnModificarCursosOperationCompleted(object arg) {
            if ((this.ModificarCursosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarCursosCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LogueoEmpleado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Empleado LogueoEmpleado(Empleado e) {
            object[] results = this.Invoke("LogueoEmpleado", new object[] {
                        e});
            return ((Empleado)(results[0]));
        }
        
        /// <remarks/>
        public void LogueoEmpleadoAsync(Empleado e) {
            this.LogueoEmpleadoAsync(e, null);
        }
        
        /// <remarks/>
        public void LogueoEmpleadoAsync(Empleado e, object userState) {
            if ((this.LogueoEmpleadoOperationCompleted == null)) {
                this.LogueoEmpleadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogueoEmpleadoOperationCompleted);
            }
            this.InvokeAsync("LogueoEmpleado", new object[] {
                        e}, this.LogueoEmpleadoOperationCompleted, userState);
        }
        
        private void OnLogueoEmpleadoOperationCompleted(object arg) {
            if ((this.LogueoEmpleadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogueoEmpleadoCompleted(this, new LogueoEmpleadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarEmpleado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Empleado BuscarEmpleado(string usu) {
            object[] results = this.Invoke("BuscarEmpleado", new object[] {
                        usu});
            return ((Empleado)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarEmpleadoAsync(string usu) {
            this.BuscarEmpleadoAsync(usu, null);
        }
        
        /// <remarks/>
        public void BuscarEmpleadoAsync(string usu, object userState) {
            if ((this.BuscarEmpleadoOperationCompleted == null)) {
                this.BuscarEmpleadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarEmpleadoOperationCompleted);
            }
            this.InvokeAsync("BuscarEmpleado", new object[] {
                        usu}, this.BuscarEmpleadoOperationCompleted, userState);
        }
        
        private void OnBuscarEmpleadoOperationCompleted(object arg) {
            if ((this.BuscarEmpleadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarEmpleadoCompleted(this, new BuscarEmpleadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistrarEmpleado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RegistrarEmpleado(Empleado e) {
            this.Invoke("RegistrarEmpleado", new object[] {
                        e});
        }
        
        /// <remarks/>
        public void RegistrarEmpleadoAsync(Empleado e) {
            this.RegistrarEmpleadoAsync(e, null);
        }
        
        /// <remarks/>
        public void RegistrarEmpleadoAsync(Empleado e, object userState) {
            if ((this.RegistrarEmpleadoOperationCompleted == null)) {
                this.RegistrarEmpleadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistrarEmpleadoOperationCompleted);
            }
            this.InvokeAsync("RegistrarEmpleado", new object[] {
                        e}, this.RegistrarEmpleadoOperationCompleted, userState);
        }
        
        private void OnRegistrarEmpleadoOperationCompleted(object arg) {
            if ((this.RegistrarEmpleadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistrarEmpleadoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificarEmlpeado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ModificarEmlpeado(Empleado e) {
            this.Invoke("ModificarEmlpeado", new object[] {
                        e});
        }
        
        /// <remarks/>
        public void ModificarEmlpeadoAsync(Empleado e) {
            this.ModificarEmlpeadoAsync(e, null);
        }
        
        /// <remarks/>
        public void ModificarEmlpeadoAsync(Empleado e, object userState) {
            if ((this.ModificarEmlpeadoOperationCompleted == null)) {
                this.ModificarEmlpeadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarEmlpeadoOperationCompleted);
            }
            this.InvokeAsync("ModificarEmlpeado", new object[] {
                        e}, this.ModificarEmlpeadoOperationCompleted, userState);
        }
        
        private void OnModificarEmlpeadoOperationCompleted(object arg) {
            if ((this.ModificarEmlpeadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarEmlpeadoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarEmpleado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EliminarEmpleado(Empleado e) {
            this.Invoke("EliminarEmpleado", new object[] {
                        e});
        }
        
        /// <remarks/>
        public void EliminarEmpleadoAsync(Empleado e) {
            this.EliminarEmpleadoAsync(e, null);
        }
        
        /// <remarks/>
        public void EliminarEmpleadoAsync(Empleado e, object userState) {
            if ((this.EliminarEmpleadoOperationCompleted == null)) {
                this.EliminarEmpleadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarEmpleadoOperationCompleted);
            }
            this.InvokeAsync("EliminarEmpleado", new object[] {
                        e}, this.EliminarEmpleadoOperationCompleted, userState);
        }
        
        private void OnEliminarEmpleadoOperationCompleted(object arg) {
            if ((this.EliminarEmpleadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarEmpleadoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarAlumno", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AgregarAlumno(Alumnos a) {
            this.Invoke("AgregarAlumno", new object[] {
                        a});
        }
        
        /// <remarks/>
        public void AgregarAlumnoAsync(Alumnos a) {
            this.AgregarAlumnoAsync(a, null);
        }
        
        /// <remarks/>
        public void AgregarAlumnoAsync(Alumnos a, object userState) {
            if ((this.AgregarAlumnoOperationCompleted == null)) {
                this.AgregarAlumnoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarAlumnoOperationCompleted);
            }
            this.InvokeAsync("AgregarAlumno", new object[] {
                        a}, this.AgregarAlumnoOperationCompleted, userState);
        }
        
        private void OnAgregarAlumnoOperationCompleted(object arg) {
            if ((this.AgregarAlumnoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarAlumnoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarAlumno", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Alumnos BuscarAlumno(int ced) {
            object[] results = this.Invoke("BuscarAlumno", new object[] {
                        ced});
            return ((Alumnos)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarAlumnoAsync(int ced) {
            this.BuscarAlumnoAsync(ced, null);
        }
        
        /// <remarks/>
        public void BuscarAlumnoAsync(int ced, object userState) {
            if ((this.BuscarAlumnoOperationCompleted == null)) {
                this.BuscarAlumnoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarAlumnoOperationCompleted);
            }
            this.InvokeAsync("BuscarAlumno", new object[] {
                        ced}, this.BuscarAlumnoOperationCompleted, userState);
        }
        
        private void OnBuscarAlumnoOperationCompleted(object arg) {
            if ((this.BuscarAlumnoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarAlumnoCompleted(this, new BuscarAlumnoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InscripcionAlumno", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InscripcionAlumno(Inscripcion insA) {
            this.Invoke("InscripcionAlumno", new object[] {
                        insA});
        }
        
        /// <remarks/>
        public void InscripcionAlumnoAsync(Inscripcion insA) {
            this.InscripcionAlumnoAsync(insA, null);
        }
        
        /// <remarks/>
        public void InscripcionAlumnoAsync(Inscripcion insA, object userState) {
            if ((this.InscripcionAlumnoOperationCompleted == null)) {
                this.InscripcionAlumnoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInscripcionAlumnoOperationCompleted);
            }
            this.InvokeAsync("InscripcionAlumno", new object[] {
                        insA}, this.InscripcionAlumnoOperationCompleted, userState);
        }
        
        private void OnInscripcionAlumnoOperationCompleted(object arg) {
            if ((this.InscripcionAlumnoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InscripcionAlumnoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarInscripcion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ListarInscripcion() {
            object[] results = this.Invoke("ListarInscripcion", new object[0]);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ListarInscripcionAsync() {
            this.ListarInscripcionAsync(null);
        }
        
        /// <remarks/>
        public void ListarInscripcionAsync(object userState) {
            if ((this.ListarInscripcionOperationCompleted == null)) {
                this.ListarInscripcionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarInscripcionOperationCompleted);
            }
            this.InvokeAsync("ListarInscripcion", new object[0], this.ListarInscripcionOperationCompleted, userState);
        }
        
        private void OnListarInscripcionOperationCompleted(object arg) {
            if ((this.ListarInscripcionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarInscripcionCompleted(this, new ListarInscripcionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarSucursal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AgregarSucursal(Sucursales s) {
            this.Invoke("AgregarSucursal", new object[] {
                        s});
        }
        
        /// <remarks/>
        public void AgregarSucursalAsync(Sucursales s) {
            this.AgregarSucursalAsync(s, null);
        }
        
        /// <remarks/>
        public void AgregarSucursalAsync(Sucursales s, object userState) {
            if ((this.AgregarSucursalOperationCompleted == null)) {
                this.AgregarSucursalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarSucursalOperationCompleted);
            }
            this.InvokeAsync("AgregarSucursal", new object[] {
                        s}, this.AgregarSucursalOperationCompleted, userState);
        }
        
        private void OnAgregarSucursalOperationCompleted(object arg) {
            if ((this.AgregarSucursalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarSucursalCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarSucursal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EliminarSucursal(Sucursales s) {
            this.Invoke("EliminarSucursal", new object[] {
                        s});
        }
        
        /// <remarks/>
        public void EliminarSucursalAsync(Sucursales s) {
            this.EliminarSucursalAsync(s, null);
        }
        
        /// <remarks/>
        public void EliminarSucursalAsync(Sucursales s, object userState) {
            if ((this.EliminarSucursalOperationCompleted == null)) {
                this.EliminarSucursalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarSucursalOperationCompleted);
            }
            this.InvokeAsync("EliminarSucursal", new object[] {
                        s}, this.EliminarSucursalOperationCompleted, userState);
        }
        
        private void OnEliminarSucursalOperationCompleted(object arg) {
            if ((this.EliminarSucursalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarSucursalCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificarSucursal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ModificarSucursal(Sucursales s) {
            this.Invoke("ModificarSucursal", new object[] {
                        s});
        }
        
        /// <remarks/>
        public void ModificarSucursalAsync(Sucursales s) {
            this.ModificarSucursalAsync(s, null);
        }
        
        /// <remarks/>
        public void ModificarSucursalAsync(Sucursales s, object userState) {
            if ((this.ModificarSucursalOperationCompleted == null)) {
                this.ModificarSucursalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarSucursalOperationCompleted);
            }
            this.InvokeAsync("ModificarSucursal", new object[] {
                        s}, this.ModificarSucursalOperationCompleted, userState);
        }
        
        private void OnModificarSucursalOperationCompleted(object arg) {
            if ((this.ModificarSucursalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarSucursalCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarSucursal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Sucursales BuscarSucursal(string sucu) {
            object[] results = this.Invoke("BuscarSucursal", new object[] {
                        sucu});
            return ((Sucursales)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarSucursalAsync(string sucu) {
            this.BuscarSucursalAsync(sucu, null);
        }
        
        /// <remarks/>
        public void BuscarSucursalAsync(string sucu, object userState) {
            if ((this.BuscarSucursalOperationCompleted == null)) {
                this.BuscarSucursalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarSucursalOperationCompleted);
            }
            this.InvokeAsync("BuscarSucursal", new object[] {
                        sucu}, this.BuscarSucursalOperationCompleted, userState);
        }
        
        private void OnBuscarSucursalOperationCompleted(object arg) {
            if ((this.BuscarSucursalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarSucursalCompleted(this, new BuscarSucursalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarSucursales", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Sucursales[] ListarSucursales() {
            object[] results = this.Invoke("ListarSucursales", new object[0]);
            return ((Sucursales[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarSucursalesAsync() {
            this.ListarSucursalesAsync(null);
        }
        
        /// <remarks/>
        public void ListarSucursalesAsync(object userState) {
            if ((this.ListarSucursalesOperationCompleted == null)) {
                this.ListarSucursalesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarSucursalesOperationCompleted);
            }
            this.InvokeAsync("ListarSucursales", new object[0], this.ListarSucursalesOperationCompleted, userState);
        }
        
        private void OnListarSucursalesOperationCompleted(object arg) {
            if ((this.ListarSucursalesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarSucursalesCompleted(this, new ListarSucursalesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cortos : Cursos {
        
        private string areaField;
        
        /// <remarks/>
        public string Area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Especializados))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Cortos))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class Cursos {
        
        private Empleado empleadosField;
        
        private Sucursales localField;
        
        private System.DateTime fecha_InicioField;
        
        private int cuposField;
        
        private int costoField;
        
        private string nombreField;
        
        private string codigoField;
        
        private string tipoCursoField;
        
        /// <remarks/>
        public Empleado Empleados {
            get {
                return this.empleadosField;
            }
            set {
                this.empleadosField = value;
            }
        }
        
        /// <remarks/>
        public Sucursales Local {
            get {
                return this.localField;
            }
            set {
                this.localField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Fecha_Inicio {
            get {
                return this.fecha_InicioField;
            }
            set {
                this.fecha_InicioField = value;
            }
        }
        
        /// <remarks/>
        public int Cupos {
            get {
                return this.cuposField;
            }
            set {
                this.cuposField = value;
            }
        }
        
        /// <remarks/>
        public int Costo {
            get {
                return this.costoField;
            }
            set {
                this.costoField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string TipoCurso {
            get {
                return this.tipoCursoField;
            }
            set {
                this.tipoCursoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Empleado {
        
        private string usuarioField;
        
        private string contraseñaField;
        
        /// <remarks/>
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        public string Contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                this.contraseñaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Inscripcion {
        
        private System.DateTime fechaField;
        
        private Alumnos alumnoField;
        
        private Cursos cursoField;
        
        /// <remarks/>
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        public Alumnos Alumno {
            get {
                return this.alumnoField;
            }
            set {
                this.alumnoField = value;
            }
        }
        
        /// <remarks/>
        public Cursos Curso {
            get {
                return this.cursoField;
            }
            set {
                this.cursoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Alumnos {
        
        private int telefonoField;
        
        private int cedulaField;
        
        private string nombreField;
        
        /// <remarks/>
        public int Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        public int Cedula {
            get {
                return this.cedulaField;
            }
            set {
                this.cedulaField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Sucursales {
        
        private string[] facilidadField;
        
        private string nombreField;
        
        private string direccionField;
        
        /// <remarks/>
        public string[] Facilidad {
            get {
                return this.facilidadField;
            }
            set {
                this.facilidadField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Especializados : Cursos {
        
        private int duracionField;
        
        /// <remarks/>
        public int Duracion {
            get {
                return this.duracionField;
            }
            set {
                this.duracionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SerializarCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SerializarCorCompletedEventHandler(object sender, SerializarCorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SerializarCorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SerializarCorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cortos Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cortos)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AgregarCursoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void EliminarCursoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void BuscarCursoCompletedEventHandler(object sender, BuscarCursoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarCursoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarCursoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cursos Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cursos)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ListarCursosCompletedEventHandler(object sender, ListarCursosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarCursosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarCursosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cursos[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cursos[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ModificarCursosCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void LogueoEmpleadoCompletedEventHandler(object sender, LogueoEmpleadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogueoEmpleadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogueoEmpleadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Empleado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Empleado)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void BuscarEmpleadoCompletedEventHandler(object sender, BuscarEmpleadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarEmpleadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarEmpleadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Empleado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Empleado)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void RegistrarEmpleadoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ModificarEmlpeadoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void EliminarEmpleadoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AgregarAlumnoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void BuscarAlumnoCompletedEventHandler(object sender, BuscarAlumnoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarAlumnoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarAlumnoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Alumnos Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Alumnos)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void InscripcionAlumnoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ListarInscripcionCompletedEventHandler(object sender, ListarInscripcionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarInscripcionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarInscripcionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AgregarSucursalCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void EliminarSucursalCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ModificarSucursalCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void BuscarSucursalCompletedEventHandler(object sender, BuscarSucursalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarSucursalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarSucursalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Sucursales Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Sucursales)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ListarSucursalesCompletedEventHandler(object sender, ListarSucursalesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarSucursalesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarSucursalesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Sucursales[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Sucursales[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591